// Mirrors the rows seeded into public.permissions (see
// supabase/migrations/20260816180004_permissions_catalog.sql). Keeping the
// keys here means the UI never hardcodes the string in more than one place.
export const PERMISSIONS = {
  MANAGE_MEMBERS: "org.manage_members",
  MANAGE_ROLES: "org.manage_roles",
  MANAGE_FORMS: "form.manage",
  TICKET_CREATE: "ticket.create",
  TICKET_VIEW: "ticket.view",
  TICKET_EDIT: "ticket.edit",
  SHIFT_MANAGE: "shift.manage",
  LEAVE_REQUEST: "leave.request",
  LEAVE_APPROVE: "leave.approve",
  ATTENDANCE_RECORD: "attendance.record",
  ATTENDANCE_VIEW: "attendance.view",
  CALENDAR_MANAGE_DAYS: "calendar.manage_days",
  REPAIR_CASE_CREATE: "repair.case.create",
  REPAIR_CASE_VIEW: "repair.case.view",
  REPAIR_CASE_RECEIVE: "repair.case.receive",
  REPAIR_CASE_DUPLICATE_OVERRIDE: "repair.case.duplicate.override",
  REPAIR_TRANSITION_TO_DIAGNOSIS: "case.transition.T01",
  REPAIR_TRANSITION_TO_INTAKE: "case.transition.T10",
  REPAIR_DIAGNOSIS_RECORD: "repair.diagnosis.record",
  REPAIR_DIAGNOSIS_FINALIZE: "repair.diagnosis.finalize",
  REPAIR_TRANSITION_TO_DECISION: "case.transition.T02",
  REPAIR_TRANSITION_TO_REPAIR: "case.transition.T03",
  REPAIR_TRANSITION_TO_REPLACEMENT: "case.transition.T04",
  REPAIR_TRANSITION_TO_RETURN_TEST: "case.transition.T05",
  REPAIR_PLAN_RECORD: "repair.plan.record",
  REPAIR_PART_RECEIVE: "repair.part.receive",
  REPAIR_PART_REQUIRE: "repair.part.require",
  REPAIR_PART_RESERVE: "repair.part.reserve",
  REPAIR_PART_CONSUME: "repair.part.consume",
  REPAIR_PART_RELEASE: "repair.part.release",
  REPAIR_PART_RETURN: "repair.part.return",
  REPAIR_COMPLETE: "repair.complete",
  REPAIR_TRANSITION_TO_TEST_FROM_REPAIR: "case.transition.T06",
  REPAIR_FUNCTIONAL_TEST_RECORD: "repair.test.record",
  REPAIR_OUTGOING_QC_RECORD: "repair.outgoing_qc.record",
  REPAIR_PAYMENT_RECORD: "repair.payment.record",
  REPAIR_PAYMENT_VERIFY: "repair.payment.verify",
  REPAIR_PART_QUARANTINE_RESTOCK: "repair.part.quarantine.restock",
  REPAIR_PART_QUARANTINE_REJECT: "repair.part.quarantine.reject",
  REPAIR_CUSTOMER_APPROVAL_RECORD: "repair.customer_approval.record",
  REPAIR_REPLACEMENT_APPROVE: "repair.replacement.approve",
  REPAIR_REPLACEMENT_STOCK_RECEIVE: "replacement.stock.receive",
  REPAIR_REPLACEMENT_STOCK_ALLOCATE: "replacement.stock.allocate",
  REPAIR_RETURN_AUTHORIZE: "repair.return.authorize",
  REPAIR_RETURN_QC_RECORD: "repair.return_qc.record",
  REPAIR_QUALITY_RELEASE: "repair.quality.release",
  REPAIR_TRANSITION_TO_DELIVERY: "case.transition.T08",
  REPAIR_TRANSITION_TO_RETEST_AFTER_DAMAGE: "case.transition.T11",
  REPAIR_DELIVERY_RECEIVE: "repair.delivery.receive",
  REPAIR_DELIVERY_DISPATCH: "repair.delivery.dispatch",
  REPAIR_DELIVERY_CONFIRM_RECEIPT: "repair.delivery.confirm_receipt",
  REPAIR_DELIVERY_INCIDENT_RECORD: "delivery.incident.record",
  REPAIR_DELIVERY_INCIDENT_FOLLOWUP: "delivery.incident.followup",
  REPAIR_DELIVERY_INCIDENT_RESOLVE: "delivery.incident.resolve",
  REPAIR_DELIVERY_RETURN_RECEIVE: "repair.delivery.return_receive",
  REPAIR_CASE_CLOSE: "case.close",
  REPAIR_CASE_ASSIGN: "case.assign",
  REPAIR_ASSIGNMENT_ACCEPT: "case.assignment.accept",
  REPAIR_ASSIGNMENT_REJECT: "case.assignment.reject",
  REPAIR_ASSIGNMENT_WITHDRAW: "case.assignment.withdraw",
  REPAIR_CUSTODY_BASELINE: "custody.baseline.record",
  REPAIR_CUSTODY_RELEASE: "custody.transfer.release",
  REPAIR_CUSTODY_ACCEPT: "custody.transfer.accept",
  REPAIR_CUSTODY_RETURN: "custody.transfer.return",
  REPAIR_CUSTODY_DISCREPANCY_RECORD: "custody.transfer.discrepancy.record",
  REPAIR_CUSTODY_DISCREPANCY_RESOLVE: "custody.transfer.discrepancy.resolve",
} as const;

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
export type PermissionScope = "own" | "all" | "team";
